CREATE DATABASE

CREATE TABLE users (
    uuidUser UNIQUEIDENTIFIER DEFAULT NEWID () NOT NULL,
    fullname NVARCHAR (100) NULL,
    birthOfDate DATE NOT NULL,
    gender BIT NOT NULL,
    avatarUrl VARCHAR(500) NOT NULL,
    createdAt DATETIME DEFAULT GETDATE () NOT NULL,
    updatedAt DATETIME DEFAULT GETDATE () NOT NULL,
    role VARCHAR(50) DEFAULT 'BUYER' NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(13) NOT NULL,
    PRIMARY KEY (uuidUser),
    UNIQUE (email),
    UNIQUE (phone)
);